# -*- makefile -*-
# Build script for kexec-mod
#
# Copyright (C) 2023 Simon Suckut.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

obj-m := ip6_tunnel.o
kexec_mod-y := ip6_tunnel.o

clean-dirs += orig

$(obj)/orig :
	mkdir -p $@

$(obj)/orig/% : | $(obj)/orig
	ln -sf $(KDIR)/kernel/$* $@

ccflags-y := -I$(src)/ -fno-unwind-tables -fno-asynchronous-unwind-tables
